# SAM CLI configuration file for rez_agent

version = 0.1

[default]
[default.global.parameters]
stack_name = "rez-agent-local"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Stage=dev"

[default.local_start_api.parameters]
warm_containers = "EAGER"
debug_port = 5858
debug_args = "-delve"
docker_network = "rez-agent-local"
skip_pull_image = true
parameter_overrides = "Stage=dev"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
debug_port = 5858
docker_network = "rez-agent-local"
skip_pull_image = true
parameter_overrides = "Stage=dev"

[default.local_invoke.parameters]
docker_network = "rez-agent-local"
skip_pull_image = true
parameter_overrides = "Stage=dev"

[default.validate.parameters]
lint = true

[default.sync.parameters]
watch = true
